#!/bin/bash
isFixWifiInstalled(){ 
	for d in $(echo $PATH | tr ':' ' ') ;
	do find $d -maxdepth 1 | grep -P "\bfixWifi\b" >/dev/null 2>&1
		test $? -eq 0 && return 0
	done 2>/dev/null
	return 1
}
test isFixWifiInstalled || $(echo fixWifi script not in \$PATH ; exit 1)
while : ;
do sleep 10
	ping -c 1 192.168.0.1 2>&1
	WLANTRUE=$?
	if [ $WLANTRUE -ne 0 ]; then
		fixWifi
		wait $!
	fi
done
