#!/bin/sh
FILE=/usr/share/V1933/variables
test -e $FILE && . $FILE
FILE=/usr/share/V1933/fixWifi
test -e $FILE && . $FILE
if nmcli --version >/dev/null 2>&1 ; then
	echo nmcli detected
	CON=$(for file in $(grep TYPE=Wireless /etc/sysconfig/network-scripts/ifcfg-* | grep -o -P '^.*?(?=:)'); do { grep -o -P '(?<=^NAME=).*' $file ; } ; done)
	DEV=$(iwconfig 2>/dev/null | grep -o --color=no -P "^wlp\S+" | sort -u)
	echo "CON: $CON"
	echo "DEV: $DEV"
	
	build(){
		echo "building module"
		sudo -p "sudo password for modprobe" modprobe -r wl
		sleep 1
		sudo akmods --force
		sleep 1
		sudo modprobe wl
		sleep 1
	}
	
	connect(){
		echo "connecting to $2 via $1"
		sudo -p "sudo password for wifi controll" nmcli con reload
		sudo nmcli dev disconnect "$1"
		sudo nmcli con up "$2"
		return $?
	}
	
	if ping -c 1 www.google.com >/dev/null 2>&1; then
		echo connected
	else
		build
		# first try last connection and last dev
		if [ -n "$lastCon" -o -n "$lastDev" ]
		then {
			sudo iwconfig "$lastDev" power on
			connect "$lastDev" "$lastCon"
			if [ $? -eq 0 ]
			then {
				echo "SUCCESS" | grep --color .\*
				exit
			}
			fi
		}
		fi
		i=0
		while [ $i -lt 10 ]; do
			((i++))
			IFS=$'\n'
			for dev in $DEV
			do {
				sudo iwconfig "$dev" power on
				for con in $CON
				do {
					if [ -z "$con" -o -z "$dev" ]; then
						continue
					fi
					con=$(echo $con|sed -e "s/\\\"//g")
					connect "$dev" "$con"
					exitStatus=$?
					if [ $exitStatus -ne 0 ]; then
						echo "FAILED, RETRYING $exitStatus"|grep --color .\*
					else
						echo "SUCCESS $exitStatus"|grep --color .\*
						FILE=/usr/share/V1933/fixWifi
						echo "lastDev=\"$dev\"" >  $FILE
						echo "lastCon=\"$con\"" >> $FILE
						exit 0
					fi
				}
				done
			}
			done
		done
	fi
fi
	
